# Generated by Django 5.2.10 on 2026-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('company_website', models.URLField(blank=True, max_length=300, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(help_text='Include country code, e.g. +91XXXXXXXXXX', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Design', 'Design'), ('Other', 'Other')], max_length=100)),
                ('experience', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Executive', 'Executive')], max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=20)),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('application_deadline', models.DateField()),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
